sudo: false

matrix:
  include:
    - os: linux
      jdk: openjdk8
      language: scala
      scala:
        - 2.13.1
      before_install:
        - docker pull daunnc/pdal-debian:2.0.0
      services:
        - docker

    - os: linux
      jdk: openjdk8
      language: scala
      scala:
        - 2.12.10
      before_install:
        - docker pull daunnc/pdal-debian:2.0.0
      services:
        - docker

    - os: osx
      osx_image: xcode9.3
      scala:
        - 2.13.1
      compiler:
        - gcc
        - clang
      before_install:
        - brew update
        - brew install pdal || true # to make travis happy

    - os: osx
      osx_image: xcode9.3
      scala:
        - 2.12.10
      compiler:
        - gcc
        - clang
      before_install:
        - brew update
        - brew install pdal || true # to make travis happy

addons:
  hostname: localhost

cache:
  directories:
   - $HOME/.m2
   - $HOME/.ivy2/cache
   - $HOME/.sbt
   - $HOME/.cache
   - $HOME/.cache/coursier
   - $HOME/Library/Caches/Homebrew

script:
  - .travis/run.sh

notifications:
  email:
    recipients:
      - gr.pomadchin@gmail.com
