/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pdal_MemoryViewReader */

#ifndef _Included_io_pdal_MemoryViewReader
#define _Included_io_pdal_MemoryViewReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pdal_MemoryViewReader
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pdal_MemoryViewReader_initialize
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_MemoryViewReader
 * Method:    pushField
 * Signature: (Lio/pdal/Field;)V
 */
JNIEXPORT void JNICALL Java_io_pdal_MemoryViewReader_pushField
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_pdal_MemoryViewReader
 * Method:    setIncrementer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pdal_MemoryViewReader_setIncrementer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pdal_MemoryViewReader
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pdal_MemoryViewReader_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
