/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pdal_TriangularMesh */

#ifndef _Included_io_pdal_TriangularMesh
#define _Included_io_pdal_TriangularMesh
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pdal_TriangularMesh
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_pdal_TriangularMesh_size
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_TriangularMesh
 * Method:    get
 * Signature: (J)Lio/pdal/Triangle;
 */
JNIEXPORT jobject JNICALL Java_io_pdal_TriangularMesh_get
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_pdal_TriangularMesh
 * Method:    hasNext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_pdal_TriangularMesh_hasNext
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_TriangularMesh
 * Method:    next
 * Signature: ()Lio/pdal/Triangle;
 */
JNIEXPORT jobject JNICALL Java_io_pdal_TriangularMesh_next
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_TriangularMesh
 * Method:    asArray
 * Signature: ()[Lio/pdal/Triangle;
 */
JNIEXPORT jobjectArray JNICALL Java_io_pdal_TriangularMesh_asArray
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_TriangularMesh
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pdal_TriangularMesh_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
