name: PDAL Java CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.13.4, 2.12.12]

    container:
      image: daunnc/pdal-ubuntu:2.2.0
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache SBT ivy cache
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT coursier cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Test
        run: |
          ./sbt ++${{matrix.scala}} "project core" test
          ./sbt ++${{matrix.scala}} "project core-scala" test 
          cd examples/pdal-jni
          ./sbt ++${{matrix.scala}} "runMain com.azavea.Main"
          ./sbt ++${{matrix.scala}} "runMain com.azavea.MainScala"

  macos:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [macos-latest]
        scala: [2.13.4, 2.12.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache SBT ivy cache
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT coursier cache
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-coursier-cache-${{ hashFiles('**/build.sbt') }}

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Cache Homebrew
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-homebrew

      - name: Install PDAL
        run: |
          brew update
          brew install pdal || true

      - name: Test
        run: |
          ./sbt ++${{matrix.scala}} "project core" test
          ./sbt ++${{matrix.scala}} "project core-scala" test 
          cd examples/pdal-jni
          ./sbt ++${{matrix.scala}} "runMain com.azavea.Main"
          ./sbt ++${{matrix.scala}} "runMain com.azavea.MainScala"
