name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['master']
    tags: [v*]
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: daunnc/pdal-ubuntu:2.3.0
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6

      - name: Test
        run: ./sbt ";project core;+test;project core-scala;+test"

      # - name: Prepare Linux Native package
        # run: |
        #   ./sbt ++${{matrix.scala}} "project core" +test && \
         #  ./sbt ++${{matrix.scala}} "project core-scala" +test

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6

      - name: Cache Homebrew
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-homebrew

      - name: Install PDAL
        run: |
          brew update && \
          brew install pdal || true

      - name: Test
        run: ./sbt ";project core;+test;project core-scala;+test"

  publish:
    runs-on: ubuntu-latest
    needs: [linux, macos]
    if: github.event_name != 'pull_request'
    env: 
      CI_SONATYPE_RELEASE: ""

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6

      - name: Release
        run: ./sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        if: ${{ env.SONATYPE_PASSWORD != '' && env.SONATYPE_USERNAME != '' }}
