name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['main']
    tags: [v*]
  # release:
    # types: [published]

jobs:
  linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        image: ['daunnc/pdal-ubuntu:2.6.0']
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # https://github.com/actions/runner/issues/2033
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - uses: coursier/cache-action@v6

      - name: Check formatting
        run: ./sbt scalafmtCheckAll

      - name: Build project
        run: ./sbt +test

  macos:
    strategy:
      matrix:
        os: [macos-latest]
        java: [8]
        distribution: [temurin]
        pdal: [2.6.2]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-activate-base: true
          activate-environment: "pdal-java"
          channels: conda-forge

      - name: Install PDAL
        run: conda install pdal=${{ matrix.pdal }}

      - name: Check formatting
        run: sbt scalafmtCheckAll

      - name: Build project
        run: sbt +test

      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: native/target/native/x86_64-darwin/bin

  publish:
    strategy:
      matrix:
        os: [ubuntu-latest]
        image: ['daunnc/pdal-ubuntu:2.5.1']
    runs-on: ${{ matrix.os }}
    needs: [linux, macos]
    container:
      image: ${{ matrix.image }}
    if: github.event_name != 'pull_request'
    env: 
      PDAL_DEPEND_ON_NATIVE: "false"
      CI_CLEAN: ""

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # https://github.com/actions/runner/issues/2033
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD

      - uses: coursier/cache-action@v6

      - uses: actions/download-artifact@v3
        with:
          name: macos
          path: native/target/native/x86_64-darwin/bin

      - name: Release
        run: ./sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        if: ${{ env.SONATYPE_PASSWORD != '' && env.SONATYPE_USERNAME != '' }}
