name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['master']
    tags: [v*]
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: daunnc/pdal-ubuntu:2.3.0
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6

      - name: Test
        run: ./sbt test-all

      - name: Prepare Linux native package
        run: ./sbt native/package

      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: native/target/*.jar

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6

      - name: Cache Homebrew
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/Homebrew
          key: ${{ runner.os }}-homebrew

      - name: Install PDAL
        run: |
          brew update && \
          brew install pdal || true

      - name: Test
        run: ./sbt test-all

      - name: Prepare MacOS native package
        run: ./sbt native/package

      - uses: actions/upload-artifact@v2
        with:
          name: macos
          path: native/target/*.jar

  publish:
    runs-on: ubuntu-latest
    needs: [linux, macos]
    # if: github.event_name != 'pull_request'
    env: 
      CI_SONATYPE_RELEASE: ""

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.8

      - name: Package native libraries
        run: ./sbt native/package

      - name: Extract native jar name
        shell: bash
        run: |
          cd native/target && \
          NATIVE_JAR_NAME=(./*.jar) && \
          rm -f $NATIVE_JAR_NAME && \
          echo "NATIVE_JAR_NAME=$NATIVE_JAR_NAME" >> $GITHUB_ENV
      
      - uses: actions/download-artifact@v2
        with:
          name: linux
          path: native/target/linux.jar

      - uses: actions/download-artifact@v2
        with:
          name: macos
          path: native/target/macos.jar

      - name: Combine native jars
        run: |
          NATIVE_JAR_NAME=${{ env.NATIVE_JAR_NAME }} && \
          mkdir tmp && \
          (cd tmp; unzip -uo ../linux.jar) && \
          (cd tmp; unzip -uo ../macos.jar) && \
          jar -cvf $NATIVE_JAR_NAME -C tmp . && \
          rm -r tmp

      - name: Release
        run: ./sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        if: ${{ env.SONATYPE_PASSWORD != '' && env.SONATYPE_USERNAME != '' }}
